// flow-typed signature: 1665934c68ca6c7dad18c9f6e2fa6562
// flow-typed version: <<STUB>>/@radix-ui/react-slider_v1.2.1/flow_v0.229.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@radix-ui/react-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@radix-ui/react-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@radix-ui/react-slider/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@radix-ui/react-slider/dist/index' {
  declare module.exports: $Exports<'@radix-ui/react-slider/dist'>;
}
declare module '@radix-ui/react-slider/dist/index.js' {
  declare module.exports: $Exports<'@radix-ui/react-slider/dist'>;
}
