// flow-typed signature: ff66dc3bb351e1fabb4c29684f4a9483
// flow-typed version: <<STUB>>/@tanstack/react-router_v1.87.9/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tanstack/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tanstack/react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tanstack/react-router/dist/esm/awaited' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/CatchBoundary' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/defer' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/fileRoute' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/isServerSideError' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/lazyRouteComponent' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/link' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/Match' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/matchContext' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/Matches' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/not-found' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/path' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/qss' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/redirects' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/renderRouteNotFound' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/root' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/route' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/router' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/routerContext' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/RouterProvider' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/SafeFragment' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/ScriptOnce' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/scroll-restoration' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/searchMiddleware' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/searchParams' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/transformer' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/Transitioner' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useBlocker' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useLoaderData' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useLoaderDeps' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useLocation' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useMatch' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useNavigate' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useParams' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useRouteContext' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useRouter' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useRouterState' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/useSearch' {
  declare module.exports: any;
}

declare module '@tanstack/react-router/dist/esm/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tanstack/react-router/dist/esm/awaited.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/awaited'>;
}
declare module '@tanstack/react-router/dist/esm/CatchBoundary.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/CatchBoundary'>;
}
declare module '@tanstack/react-router/dist/esm/defer.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/defer'>;
}
declare module '@tanstack/react-router/dist/esm/fileRoute.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/fileRoute'>;
}
declare module '@tanstack/react-router/dist/esm/index' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm'>;
}
declare module '@tanstack/react-router/dist/esm/index.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm'>;
}
declare module '@tanstack/react-router/dist/esm/isServerSideError.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/isServerSideError'>;
}
declare module '@tanstack/react-router/dist/esm/lazyRouteComponent.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/lazyRouteComponent'>;
}
declare module '@tanstack/react-router/dist/esm/link.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/link'>;
}
declare module '@tanstack/react-router/dist/esm/Match.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/Match'>;
}
declare module '@tanstack/react-router/dist/esm/matchContext.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/matchContext'>;
}
declare module '@tanstack/react-router/dist/esm/Matches.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/Matches'>;
}
declare module '@tanstack/react-router/dist/esm/not-found.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/not-found'>;
}
declare module '@tanstack/react-router/dist/esm/path.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/path'>;
}
declare module '@tanstack/react-router/dist/esm/qss.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/qss'>;
}
declare module '@tanstack/react-router/dist/esm/redirects.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/redirects'>;
}
declare module '@tanstack/react-router/dist/esm/renderRouteNotFound.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/renderRouteNotFound'>;
}
declare module '@tanstack/react-router/dist/esm/root.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/root'>;
}
declare module '@tanstack/react-router/dist/esm/route.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/route'>;
}
declare module '@tanstack/react-router/dist/esm/router.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/router'>;
}
declare module '@tanstack/react-router/dist/esm/routerContext.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/routerContext'>;
}
declare module '@tanstack/react-router/dist/esm/RouterProvider.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/RouterProvider'>;
}
declare module '@tanstack/react-router/dist/esm/SafeFragment.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/SafeFragment'>;
}
declare module '@tanstack/react-router/dist/esm/ScriptOnce.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/ScriptOnce'>;
}
declare module '@tanstack/react-router/dist/esm/scroll-restoration.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/scroll-restoration'>;
}
declare module '@tanstack/react-router/dist/esm/searchMiddleware.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/searchMiddleware'>;
}
declare module '@tanstack/react-router/dist/esm/searchParams.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/searchParams'>;
}
declare module '@tanstack/react-router/dist/esm/transformer.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/transformer'>;
}
declare module '@tanstack/react-router/dist/esm/Transitioner.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/Transitioner'>;
}
declare module '@tanstack/react-router/dist/esm/useBlocker.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useBlocker'>;
}
declare module '@tanstack/react-router/dist/esm/useLoaderData.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useLoaderData'>;
}
declare module '@tanstack/react-router/dist/esm/useLoaderDeps.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useLoaderDeps'>;
}
declare module '@tanstack/react-router/dist/esm/useLocation.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useLocation'>;
}
declare module '@tanstack/react-router/dist/esm/useMatch.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useMatch'>;
}
declare module '@tanstack/react-router/dist/esm/useNavigate.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useNavigate'>;
}
declare module '@tanstack/react-router/dist/esm/useParams.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useParams'>;
}
declare module '@tanstack/react-router/dist/esm/useRouteContext.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useRouteContext'>;
}
declare module '@tanstack/react-router/dist/esm/useRouter.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useRouter'>;
}
declare module '@tanstack/react-router/dist/esm/useRouterState.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useRouterState'>;
}
declare module '@tanstack/react-router/dist/esm/useSearch.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/useSearch'>;
}
declare module '@tanstack/react-router/dist/esm/utils.js' {
  declare module.exports: $Exports<'@tanstack/react-router/dist/esm/utils'>;
}
