// flow-typed signature: 1a2a09a032be3f182665d7e5f07fdf4b
// flow-typed version: <<STUB>>/clsx_v2.1.1/flow_v0.229.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clsx/dist/clsx' {
  declare module.exports: any;
}

declare module 'clsx/dist/clsx.min' {
  declare module.exports: any;
}

declare module 'clsx/dist/lite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clsx/dist/clsx.js' {
  declare module.exports: $Exports<'clsx/dist/clsx'>;
}
declare module 'clsx/dist/clsx.min.js' {
  declare module.exports: $Exports<'clsx/dist/clsx.min'>;
}
declare module 'clsx/dist/lite.js' {
  declare module.exports: $Exports<'clsx/dist/lite'>;
}
