// flow-typed signature: 81d7e577948a38832dade8af649891d6
// flow-typed version: <<STUB>>/tailwind-merge_v2.5.5/flow_v0.229.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwind-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwind-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwind-merge/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module 'tailwind-merge/dist/es5/bundle-cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwind-merge/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'tailwind-merge/dist/bundle-cjs'>;
}
declare module 'tailwind-merge/dist/es5/bundle-cjs.js' {
  declare module.exports: $Exports<'tailwind-merge/dist/es5/bundle-cjs'>;
}
