// flow-typed signature: 98b5f7370a1d562b87a78f357a103319
// flow-typed version: <<STUB>>/@react-three/fiber_v8.17.10/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-three/fiber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-three/fiber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-three/fiber/dist/events-09858d86.cjs.prod' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/events-31675df9.cjs.dev' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/events-321b05fb.esm' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/react-three-fiber.cjs.dev' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/react-three-fiber.cjs' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/react-three-fiber.cjs.prod' {
  declare module.exports: any;
}

declare module '@react-three/fiber/dist/react-three-fiber.esm' {
  declare module.exports: any;
}

declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev' {
  declare module.exports: any;
}

declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs' {
  declare module.exports: any;
}

declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs.prod' {
  declare module.exports: any;
}

declare module '@react-three/fiber/native/dist/react-three-fiber-native.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-three/fiber/dist/events-09858d86.cjs.prod.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/events-09858d86.cjs.prod'>;
}
declare module '@react-three/fiber/dist/events-31675df9.cjs.dev.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/events-31675df9.cjs.dev'>;
}
declare module '@react-three/fiber/dist/events-321b05fb.esm.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/events-321b05fb.esm'>;
}
declare module '@react-three/fiber/dist/react-three-fiber.cjs.dev.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/react-three-fiber.cjs.dev'>;
}
declare module '@react-three/fiber/dist/react-three-fiber.cjs.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/react-three-fiber.cjs'>;
}
declare module '@react-three/fiber/dist/react-three-fiber.cjs.prod.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/react-three-fiber.cjs.prod'>;
}
declare module '@react-three/fiber/dist/react-three-fiber.esm.js' {
  declare module.exports: $Exports<'@react-three/fiber/dist/react-three-fiber.esm'>;
}
declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js' {
  declare module.exports: $Exports<'@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev'>;
}
declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs.js' {
  declare module.exports: $Exports<'@react-three/fiber/native/dist/react-three-fiber-native.cjs'>;
}
declare module '@react-three/fiber/native/dist/react-three-fiber-native.cjs.prod.js' {
  declare module.exports: $Exports<'@react-three/fiber/native/dist/react-three-fiber-native.cjs.prod'>;
}
declare module '@react-three/fiber/native/dist/react-three-fiber-native.esm.js' {
  declare module.exports: $Exports<'@react-three/fiber/native/dist/react-three-fiber-native.esm'>;
}
